/** Fields that come from actual file metadata (always real) */
export interface FileMetadata {
  fileName: string;
  fileSize: string;
  uploadedAt: string;
  /** Duration extracted from file metadata, if available */
  fileDuration: string | null;
}

/** Fields that will come from a real audio processing engine in the future.
 *  Currently populated with preview/demo values. */
export interface AnalysisMetrics {
  estimated_reference_hz: number;
  tuning_offset_cents: number;
  tuning_label: string;
  bpm: number;
  energy_score: number;
  mood_label: string;
  mood_emoji: string;
  key_signature: string;
  bass_intensity: number;
  brightness: number;
  confidence_score: number;
  spectrum: number[];
}

export interface AnalysisResult extends FileMetadata, AnalysisMetrics {
  id: string;
  /** Whether metrics were generated by a real engine or preview logic */
  analysisSource: "preview" | "engine";

  // ── Legacy aliases (kept for backward compat with existing saved data) ──
  analyzedAt: string;
  tuningReference: number;
  tuningLabel: string;
  tuningDeviation: number;
  energy: number;
  mood: string;
  moodEmoji: string;
  duration: string;
  key: string;
  bassIntensity: number;
  confidence: number;
}

const moods = [
  { label: "Energetic", emoji: "⚡" },
  { label: "Melancholic", emoji: "🌧" },
  { label: "Uplifting", emoji: "☀️" },
  { label: "Dark", emoji: "🌑" },
  { label: "Dreamy", emoji: "✨" },
  { label: "Aggressive", emoji: "🔥" },
  { label: "Calm", emoji: "🌊" },
  { label: "Euphoric", emoji: "🎆" },
];

const keys = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"];
const scales = ["Major", "Minor"];

const tuningRefs = [
  { hz: 432, label: "432 Hz — Verdi tuning" },
  { hz: 440, label: "440 Hz — Standard" },
  { hz: 442, label: "442 Hz — European orchestral" },
  { hz: 444, label: "444 Hz — Bright concert" },
];

export function generateMockAnalysis(fileName: string, fileSize: number): AnalysisResult {
  const tuning = tuningRefs[Math.floor(Math.random() * tuningRefs.length)];
  const mood = moods[Math.floor(Math.random() * moods.length)];
  const spectrum = Array.from({ length: 32 }, () => Math.random() * 0.8 + 0.1);
  const minutes = Math.floor(Math.random() * 5) + 2;
  const seconds = Math.floor(Math.random() * 60);
  const deviation = parseFloat((Math.random() * 4 - 2).toFixed(1));
  const bpm = Math.floor(Math.random() * 80) + 80;
  const energy = Math.floor(Math.random() * 40) + 60;
  const keyStr = `${keys[Math.floor(Math.random() * keys.length)]} ${scales[Math.floor(Math.random() * scales.length)]}`;
  const bass = Math.floor(Math.random() * 40) + 40;
  const bright = Math.floor(Math.random() * 50) + 30;
  const conf = Math.floor(Math.random() * 15) + 78;
  const sizeStr = fileSize > 1024 * 1024
    ? `${(fileSize / (1024 * 1024)).toFixed(1)} MB`
    : `${(fileSize / 1024).toFixed(0)} KB`;
  const durationStr = `${minutes}:${seconds.toString().padStart(2, "0")}`;
  const now = new Date().toISOString();

  return {
    id: crypto.randomUUID(),
    analysisSource: "preview",

    // File metadata (real)
    fileName,
    fileSize: sizeStr,
    uploadedAt: now,
    fileDuration: null, // Would come from real file metadata parsing

    // Analysis metrics (preview/demo)
    estimated_reference_hz: tuning.hz,
    tuning_offset_cents: deviation,
    tuning_label: tuning.label,
    bpm,
    energy_score: energy,
    mood_label: mood.label,
    mood_emoji: mood.emoji,
    key_signature: keyStr,
    bass_intensity: bass,
    brightness: bright,
    confidence_score: conf,
    spectrum,

    // Legacy aliases
    analyzedAt: now,
    tuningReference: tuning.hz,
    tuningLabel: tuning.label,
    tuningDeviation: deviation,
    energy,
    mood: mood.label,
    moodEmoji: mood.emoji,
    duration: durationStr,
    key: keyStr,
    bassIntensity: bass,
    confidence: conf,
  };
}
